--OPERACIONES CON EL LDD
--CREAMOS LA BASE DE DATOS HOTEL_PARAISO

--CREAR LA TABLA HABITACIONES
CREATE TABLE habitaciones
(
	NroHab	INTEGER PRIMARY KEY NOT NULL,
	tipo	VARCHAR(20),
	precio	MONEY,
	cable 	VARCHAR(2),
	BañoPrivado	VARCHAR(2),
	telefono	INTEGER
);

--ADICIONAR EL CAMPO INTERNET Y DISPONIBLE EN LA TABLA HABITACIONES
ALTER TABLE habitaciones
ADD internet VARCHAR(2);

ALTER TABLE habitaciones
ADD disponible VARCHAR(2);


--ELIMINAR EL CAMPO DE INTERNET DE LA TABLA HABITACIONES
ALTER TABLE habitaciones
DROP COLUMN internet;

--MODIFICAR EL TIPO DE DATO DE LA COLUMNA TELEFONO A VARCHAR(2)
--DE LA TABLA HABITACIONES
ALTER TABLE habitaciones
ALTER COLUMN telefono SET DATA TYPE VARCHAR(2);


--CAMBIAR ELNOMBRE DE LA TABLA HABITACIONES POR HABITACION
ALTER TABLE habitaciones RENAME TO habitacion;



--CAMBIAR EL NOMBRE DE LA COLUMNA PRECIO POR COSTO EN LA
--TABLA HABITACION
ALTER TABLE habitacion
RENAME COLUMN precio TO costo;

--eliminar la tabla habitacion
DROP TABLE habitacion;
